version: '3.8'

services:
  postgres_nlw:
    container_name: Ex1DevOps
    image: postgres
    ports:
      - "8834:8834"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
